package edu.gmu.hodum.sei.gesture.service;

public enum RecognizerState {
		MAIN_DEACTIVATED,
		MAIN_ACTIVATED,
		LEARNING_MAIN_DEACTIVATED,
		LEARNING_MAIN_ACTIVATED,
		TEST_MAIN_ACTIVATED,
		TEST_MAIN_DEACTIVATED,
		CHOICE_DEACTIVATED,
		CHOICE_ACTIVATED,
		LEARNING_CHOICE_ACTIVATED,
		LEARNING_CHOICE_DEACTIVATED,
		TEST_CHOICE_ACTIVATED,
		TEST_CHOICE_DEACTIVATED,
		CONFIGURING,
		COMPASS_MODE
}
