#!/system/bin/sh
set -e
#!/system/bin/sh
set -e

PATH="${PATH}:/data/data/cs.edu895/files"
load() {

insmod /system/lib/modules/bcm4329.ko firmware_path=/vendor/firmware/fw_bcm4329.bin nvram_path=/proc/calibration
ifconfig eth0 192.168.13.54 netmask 255.255.255.0
ifconfig eth0 up
iwconfig eth0 mode ad-hoc
iwconfig eth0 essid Testing
iwconfig eth0 channel 6 #this line gave an error but seemed to work?? iwconfig eth0 commit
}

up (){
ifconfig eth0 up
}

$1